import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import { ProtectedAdminRoute } from '../components/ProtectedAdminRoute';
import { api } from '../lib/api';

interface AvailabilityData { rules: any[]; overrides: any[]; }
export const AdminAvailabilityPage: React.FC = () => <ProtectedAdminRoute><AvailabilityContent /></ProtectedAdminRoute>;
const AvailabilityContent: React.FC = () => {
  const [data, setData] = useState<AvailabilityData | null>(null); const [error, setError] = useState('');
  const load = () => api.adminAvailability().then(result => setData(result as AvailabilityData)).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Loading failed.'));
  useEffect(() => { void load(); }, []);
  const updateRule = async (rule: any) => { try { await api.adminAvailability({ action: 'update-rule', id: rule.id, startLocal: rule.start_local, endLocal: rule.end_local, timezone: rule.timezone, slotIntervalMinutes: Number(rule.slot_interval_minutes), bufferBeforeMinutes: Number(rule.buffer_before_minutes), bufferAfterMinutes: Number(rule.buffer_after_minutes), active: rule.active }); load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Update failed.'); } };
  const addOverride = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const fields = new FormData(event.currentTarget); try { await api.adminAvailability({ action: 'add-override', kind: fields.get('kind'), startsAt: new Date(String(fields.get('startsAt'))).toISOString(), endsAt: new Date(String(fields.get('endsAt'))).toISOString(), reason: fields.get('reason') }); event.currentTarget.reset(); load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Override creation failed.'); } };
  return <div className="min-h-screen pt-14"><div className="max-w-5xl mx-auto px-4 sm:px-6 py-14"><Link to="/admin" className="inline-flex items-center gap-2 font-mono text-[10px] text-[#4a4a54] hover:text-[#c8a96b] mb-10"><ArrowLeft size={11} /> ADMIN DASHBOARD</Link><header className="mb-8"><p className="font-mono text-[10px] text-[#c8a96b] tracking-widest">AVAILABILITY CONTROL</p><h1 className="mt-2 font-display text-4xl font-bold uppercase">Hours & Overrides</h1></header>{error && <p role="alert" className="mb-5 font-mono text-xs text-red-400">{error}</p>}<section><h2 className="font-mono text-xs text-[#f0efea] mb-4">WEEKLY RULES</h2><div className="space-y-3">{data?.rules.map(rule => <RuleRow key={rule.id} rule={rule} onSave={updateRule} />)}</div></section><section className="mt-10 grid lg:grid-cols-[.8fr_1.2fr] gap-6"><form onSubmit={addOverride} className="border border-[#1e1e22] bg-[#0f0f10] p-5 space-y-4"><h2 className="font-mono text-xs text-[#f0efea]">ADD OVERRIDE</h2><div><label className="form-label">TYPE</label><select name="kind" className="form-control"><option>BLOCKED</option><option>VACATION</option><option>CUSTOM</option></select></div><div><label className="form-label">START</label><input name="startsAt" required type="datetime-local" className="form-control" /></div><div><label className="form-label">END</label><input name="endsAt" required type="datetime-local" className="form-control" /></div><div><label className="form-label">REASON</label><input name="reason" className="form-control" /></div><button className="w-full inline-flex justify-center gap-2 bg-[#c8a96b] py-3 font-mono text-xs font-bold text-[#0a0a0b]"><Plus size={12} /> ADD OVERRIDE</button></form><div><h2 className="font-mono text-xs text-[#f0efea] mb-4">SCHEDULED OVERRIDES</h2><div className="space-y-3">{data?.overrides.map(override => <div key={override.id} className="flex justify-between gap-4 border border-[#1e1e22] bg-[#0f0f10] p-4"><div><p className="font-mono text-xs text-[#c8a96b]">{override.kind}</p><p className="mt-2 font-mono text-[10px] text-[#8a8a96]">{new Date(override.starts_at).toLocaleString()} — {new Date(override.ends_at).toLocaleString()}</p><p className="mt-2 text-xs text-[#8a8a96]">{override.reason}</p></div><button onClick={async () => { await api.adminAvailability({ action: 'delete-override', id: override.id }); load(); }} className="text-red-400"><Trash2 size={14} /></button></div>)}</div></div></section></div></div>;
};
const RuleRow: React.FC<{ rule: any; onSave: (rule: any) => void }> = ({ rule, onSave }) => { const [current, setCurrent] = useState(rule); return <div className="grid grid-cols-2 sm:grid-cols-[.5fr_1fr_1fr_1fr_auto] gap-3 items-end border border-[#1e1e22] bg-[#0f0f10] p-4"><div><label className="form-label">DAY</label><p className="font-mono text-xs text-[#f0efea]">{['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'][current.weekday]}</p></div><Input label="START" value={current.start_local} onChange={value => setCurrent({ ...current, start_local: value })} /><Input label="END" value={current.end_local} onChange={value => setCurrent({ ...current, end_local: value })} /><Input label="INTERVAL" type="number" value={String(current.slot_interval_minutes)} onChange={value => setCurrent({ ...current, slot_interval_minutes: value })} /><button onClick={() => onSave(current)} className="border border-[#c8a96b]/40 px-3 py-2 font-mono text-[10px] text-[#c8a96b]">SAVE</button></div>; };
const Input: React.FC<{ label: string; value: string; onChange: (value: string) => void; type?: string }> = ({ label, value, onChange, type = 'time' }) => <div><label className="form-label">{label}</label><input className="form-control" type={type} value={value} onChange={event => onChange(event.target.value)} /></div>;
