import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CalendarX2, CheckCircle2, Loader2 } from 'lucide-react';
import { api } from '../lib/api';
import { formatLocalDate, formatLocalTime } from '../lib/booking';
import { isBackendConfigured } from '../lib/supabase';

export const VisitorBookingActionPage: React.FC<{ mode: 'cancel' | 'reschedule' }> = ({ mode }) => {
  const { token = '' } = useParams();
  const [booking, setBooking] = useState<any>(null); const [state, setState] = useState<'loading' | 'ready' | 'working' | 'complete' | 'error'>('loading'); const [error, setError] = useState('');
  useEffect(() => { if (!isBackendConfigured) { setError('Secure scheduling service is not configured.'); setState('error'); return; } api.visitorBooking(token, mode).then(result => { setBooking((result as any).booking); setState('ready'); }).catch(requestError => { setError(requestError instanceof Error ? requestError.message : 'Booking link is invalid or has expired.'); setState('error'); }); }, [mode, token]);
  const cancel = async () => { setState('working'); try { await api.visitorBookingAction({ token, action: 'cancel' }); setState('complete'); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Cancellation failed.'); setState('error'); } };
  if (mode === 'reschedule' && state === 'ready') return <RedirectToScheduler booking={booking} />;
  return <div className="min-h-screen pt-14 flex items-center justify-center px-4"><div className="w-full max-w-lg border border-[#1e1e22] bg-[#0f0f10] p-7 text-center">{state === 'loading' || state === 'working' ? <><Loader2 size={26} className="mx-auto animate-spin text-[#c8a96b]" /><p className="mt-4 font-mono text-xs text-[#8a8a96]">{state === 'working' ? 'PROCESSING REQUEST…' : 'VERIFYING BOOKING LINK…'}</p></> : state === 'error' ? <><CalendarX2 size={28} className="mx-auto text-red-400" /><p className="mt-4 font-mono text-xs text-red-400">{error}</p><Link to="/schedule" className="inline-block mt-6 font-mono text-xs text-[#c8a96b]">SCHEDULE A NEW MEETING</Link></> : state === 'complete' ? <><CheckCircle2 size={30} className="mx-auto text-[#4ade80]" /><h1 className="mt-4 font-mono text-sm text-[#f0efea]">MEETING CANCELLED</h1><p className="mt-3 text-sm text-[#8a8a96]">The time has been released.</p><Link to="/schedule" className="inline-block mt-6 font-mono text-xs text-[#c8a96b]">SCHEDULE A NEW MEETING</Link></> : booking && <><CalendarX2 size={28} className="mx-auto text-[#c8a96b]" /><p className="mt-4 font-mono text-[10px] text-[#c8a96b]">CANCEL MEETING</p><h1 className="mt-3 font-mono text-sm text-[#f0efea]">{booking.meeting_types?.name}</h1><p className="mt-3 text-sm text-[#8a8a96]">{formatLocalDate(booking.start_time_utc, booking.visitor_timezone)} · {formatLocalTime(booking.start_time_utc, booking.visitor_timezone)}</p><button onClick={cancel} className="mt-7 bg-red-500/90 px-5 py-3 font-mono text-xs font-bold text-white">CONFIRM CANCELLATION</button></>}</div></div>;
};
const RedirectToScheduler: React.FC<{ booking: any }> = ({ booking }) => <div className="min-h-screen pt-14 flex items-center justify-center px-4"><div className="w-full max-w-lg border border-[#1e1e22] bg-[#0f0f10] p-7 text-center"><CalendarX2 size={28} className="mx-auto text-[#c8a96b]" /><p className="mt-4 font-mono text-[10px] text-[#c8a96b]">RESCHEDULING</p><p className="mt-3 text-sm text-[#8a8a96]">To select another available time for {booking.meeting_types?.name}, begin a new secure request. Your current booking remains active until you cancel it.</p><Link to="/schedule" className="inline-block mt-7 bg-[#c8a96b] px-5 py-3 font-mono text-xs font-bold text-[#0a0a0b]">CHOOSE A NEW TIME</Link></div></div>;
